Upgrade to poc-framework 0.1.6 for tempfile fix
Issue: https://github.com/neodyme-labs/solana-poc-framework/issues/2.

Fixes error messages like
```
thread 'main' panicked at 'Unable to create data file /tmp/.tmpt2Dr5x/0.6 in current dir(Ok("/home/redacted/code/redacted")): Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/danah/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-runtime-1.8.8/src/append_vec.rs:188:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```